all:
    children:
        SITE1:
            children:
                SITE1_NXOS:
        SITE2:
            children:
                SITE2_IOSXR:
        IOSXR:
            children:
                SITE2_IOSXR:
        NXOS:
            children:
                SITE1_NXOS:
        SITE2_IOSXR:
            hosts:
                SITE2HOST1:
                    ansible_host: 127.0.1.3
                SITE2HOST1:
                    ansible_host: 127.0.1.4
        SITE1_NXOS:
            hosts:
                SITE1HOST1:
                    ansible_host: 127.0.1.1
                SITE1HOST1:
                    ansible_host: 127.0.1.2

    